# Generated by Django 4.2.1 on 2023-05-21 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('categorie', multiselectfield.db.fields.MultiSelectField(choices=[('Backend', 'Backend'), ('Fullstack', 'FullStack'), ('SQL', 'SQL'), ('MongoDB', 'mongodb'), ('Design', 'Design')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField()),
                ('github', models.URLField()),
                ('logo', models.URLField(blank=True, null=True)),
                ('technologies', multiselectfield.db.fields.MultiSelectField(choices=[('Django', 'Django'), ('Flask', 'Flask'), ('Python', 'Python'), ('SQL', 'SQL'), ('NoSQL', 'NoSQL'), ('Docker', 'Docker'), ('TailwindCSS', 'tailwind'), ('Bootstrap', 'Bootstrap'), ('HTMX', 'Htmx'), ('Hyperscript', 'Hyperscript')], max_length=20)),
                ('clients', models.CharField(max_length=50)),
                ('lien_clients', models.URLField(blank=True, null=True)),
                ('problemes_resolus', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
